### ISSUE TITLE
Actually, your script is written in Python 3

### ISSUE THREAD

**Issue by RoiEXLab** [carykh/jumpcutter#5]
I just checked the script.
You're using `print` as a function, and using `range()` to iterate over numbers, so looks like python 3 to me.
You should probably just remove the disclaimer in your readme and everyone is going to be fine.

**Comment by carykh** [comment]
I think you're right. oaops

**Comment by ClashLuke** [comment]
@carykh I tried it out. Your scripts run on python2, but I would highly recommend adding version numbers to the `requirements.txt`, since your scripts do not run with Python2 + Python3-NumPy. 
I am sure your scripts run on Py2 not Py3, because the sound is completely asynchronous when using Python3 while everything works perfectly fine on Py2.

**Comment by RoiEXLab** [comment]
Interesting.
Looks like @carykh somehow managed to write a python script that is written in a python 2 syntax with formatting so terrible (or ingenious depending on your view) that works for python 3 as well.
On python 2 the parentheses after print are simply ignored, while python 3 interprets them as the normal function parentheses.
I just learned that `range()` exists for python 2 as well, but isn't intended to be used for loops because it constructs a complete list instead of a simple generator.

I haven't quite figured out yet why this has anything to do with sound problems, but I'm sure there's a perfectly reasonable explanation for that as well.
