### ISSUE TITLE
[Enhancement] Use ffmpeg-python instead of FFmpeg in subprocess pipeline.

### ISSUE THREAD

**Issue by abhiTronix** [carykh/jumpcutter#53]
The speed is throttling in my tests when executing FFmpeg commands in subprocess pipeline. We can shift to [ffmpeg-python](https://github.com/kkroening/ffmpeg-python) project which is a python wrapper around FFmpeg for achieving better performance.

**Comment by Bottersnike** [comment]
Although ffmpeg-python may be a nicer programatic interface, it's not going to be anoy faster. The bottneck will be your hardware, as this code merely uses subprocess to call out to the installed copy of ffmpeg. Due to the natue of video encoding, the bottleneck is going to be you CPU, not GPU, so if it's running slow try allocating more cores, increasing the process priority (be careful with this one), or just getting a better PC.

**Comment by abhiTronix** [comment]
@Bottersnike yep you may be right, but think, switching from the subpocess pipeline to native API will make it easier, as it contains pre-implemented functions/methods to access FFmpeg rather than manually sorting each data/information.
